const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('anydeksApi', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setServerUrl: (value) => ipcRenderer.invoke('config:set-server-url', value),
  setNetworkConfig: (value) => ipcRenderer.invoke('config:set-network', value),
  setFixedPassword: (value) => ipcRenderer.invoke('config:set-fixed-password', value),
  authorizeAdmin: (value) => ipcRenderer.invoke('admin:authorize', value),
  getAdminDashboard: () => ipcRenderer.invoke('admin:get-dashboard'),
  approveLicenseRequest: (payload) => ipcRenderer.invoke('admin:approve-request', payload),
  deleteLicenseRequest: (deviceCode) => ipcRenderer.invoke('admin:delete-request', deviceCode),
  upsertLicense: (payload) => ipcRenderer.invoke('admin:upsert-license', payload),
  deleteLicense: (deviceCode) => ipcRenderer.invoke('admin:delete-license', deviceCode),
  getSecretState: () => ipcRenderer.invoke('config:get-secret-state'),
  getLicenseStatus: () => ipcRenderer.invoke('license:get-status'),
  refreshLicenseStatus: () => ipcRenderer.invoke('license:refresh'),
  requestLicense: () => ipcRenderer.invoke('license:request'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check-now'),
  configureWakeOnLan: () => ipcRenderer.invoke('wol:configure'),
  wakeDevice: (payload) => ipcRenderer.invoke('wol:wake', payload),
  validateCredential: (value) => ipcRenderer.invoke('auth:validate-credential', value),
  getDisplayInfo: () => ipcRenderer.invoke('desktop:get-display-info'),
  listDesktopSources: () => ipcRenderer.invoke('desktop:list-sources'),
  setDesktopSource: (value) => ipcRenderer.invoke('desktop:set-source', value),
  performInput: (payload) => ipcRenderer.invoke('input:perform', payload),
  saveIncomingFile: (payload) => ipcRenderer.invoke('files:save', payload),
  onOpenAdminPanel: (callback) => ipcRenderer.on('admin:open-panel', () => callback()),
});